import { ImageEditor, IMAGE_FORMAT } from './image-editor.js';
const $=s=>document.querySelector(s), state={data:null,listId:null,entryId:null,selected:new Set(),undo:[],redo:[],dirty:false,pendingDiff:null,manifest:null};
const statuses=['manquante','importee','a_cadrer','a_verifier','validee','verrouillee','source_cassee','conflit'];
let editor;
async function load(){state.data=await (await fetch('/api/workspace')).json();state.listId=state.data.lists.find(l=>!l.deletedAt)?.id;statuses.forEach(s=>$('#f-status').add(new Option(s.replaceAll('_',' '),s)));render();status('enregistré')}
function status(s){$('#status').textContent=s}
function snapshot(){state.undo.push(JSON.stringify(state.data));if(state.undo.length>40)state.undo.shift();state.redo=[]}
function change(fn){snapshot();fn();state.dirty=true;status('modifications en cours');render()}
function currentList(){return state.data.lists.find(l=>l.id===state.listId)}
function entries(){return state.data.entries.filter(e=>e.listId===state.listId&&!e.deletedAt)}
function render(){renderNav();renderTable();renderDetail()}
function renderNav(){const q=$('#search').value.toLowerCase();$('#nav').innerHTML=state.data.categories.filter(c=>!c.deletedAt).sort((a,b)=>a.order-b.order).map(c=>`<div class="category">${esc(c.name)}</div>${state.data.lists.filter(l=>l.categoryId===c.id&&!l.deletedAt&&(!q||l.name.toLowerCase().includes(q)||state.data.entries.some(e=>e.listId===l.id&&e.name.toLowerCase().includes(q)))).sort((a,b)=>a.order-b.order).map(l=>`<button class="list ${l.id===state.listId?'active':''}" data-list="${l.id}">${esc(l.icon)} ${esc(l.name)} <small>(${state.data.entries.filter(e=>e.listId===l.id&&!e.deletedAt).length})</small></button>`).join('')}`).join('')}
function renderTable(){const list=currentList();if(!list)return;$('#list-title').textContent=list.name;const es=entries().filter(e=>!$('#search').value||JSON.stringify(e).toLowerCase().includes($('#search').value.toLowerCase()));const missing=es.filter(e=>['manquante','source_cassee','conflit'].includes(e.image?.status)).length;$('#metrics').textContent=`${es.length} entrées · ${missing} image(s) à traiter`;$('#thead').innerHTML=`<tr><th>✓</th><th>N°</th><th>Image</th><th>Nom</th>${list.columns.slice(2).map(c=>`<th>${esc(c)}</th>`).join('')}</tr>`;$('#tbody').innerHTML=es.sort((a,b)=>a.order-b.order).map(e=>`<tr data-entry="${e.id}" class="${state.selected.has(e.id)?'selected':''}"><td><input type="checkbox" ${state.selected.has(e.id)?'checked':''}></td><td contenteditable data-field="number">${esc(e.number)}</td><td>${e.image?.thumb?`<img loading="lazy" src="/${esc(e.image.thumb)}">`:'—'}</td><td contenteditable data-field="name">${esc(e.name)}</td>${list.columns.slice(2).map(c=>`<td contenteditable data-extra="${esc(c)}">${esc(e.fields?.[c]||'')}</td>`).join('')}</tr>`).join('')}
function renderDetail(){const e=state.data.entries.find(x=>x.id===state.entryId);$('#empty').hidden=!!e;$('#form').hidden=!e;if(!e)return;for(const [id,key] of [['f-id','id'],['f-number','number'],['f-name','name'],['f-title','title'],['f-subtitle','subtitle'],['f-description','description'],['f-extra','extraText'],['f-wiki','wikipedia']])$(id.startsWith('#')?id:'#'+id).value=e[key]||'';$('#f-status').value=e.image?.status||'manquante';$('#f-locked').checked=!!e.image?.locked;$('#open-wiki').href=e.wikipedia||'#';$('#dynamic-fields').innerHTML=Object.entries(e.fields||{}).map(([k,v])=>`<label>${esc(k)}<input data-dynamic="${esc(k)}" value="${esc(v)}"></label>`).join('')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function save(){const r=await fetch('/api/workspace',{method:'PUT',headers:{'Content-Type':'application/json','If-Match':state.data.revision},body:JSON.stringify(state.data)});const j=await r.json();if(!r.ok){status('erreur');return alert(j.error||j.errors?.join('\n'))}state.data.revision=j.revision;state.data.updatedAt=j.updatedAt;state.dirty=false;status('enregistré')}
$('#nav').onclick=e=>{const id=e.target.closest('[data-list]')?.dataset.list;if(id){state.listId=id;state.entryId=null;state.selected.clear();$('aside').classList.remove('mobile-open');render()}};
$('#mobile-menu').onclick=()=>$('aside').classList.add('mobile-open');$('#close-nav').onclick=()=>$('aside').classList.remove('mobile-open');
$('#tbody').onclick=e=>{const tr=e.target.closest('tr');if(!tr)return;const id=tr.dataset.entry;if(e.target.type==='checkbox'){e.target.checked?state.selected.add(id):state.selected.delete(id)}else state.entryId=id;render()};
$('#tbody').oninput=e=>{const tr=e.target.closest('tr'),entry=state.data.entries.find(x=>x.id===tr?.dataset.entry);if(!entry)return;if(!state.dirty)snapshot();if(e.target.dataset.field)entry[e.target.dataset.field]=e.target.textContent;if(e.target.dataset.extra)entry.fields[e.target.dataset.extra]=e.target.textContent;state.dirty=true;status('modifications en cours')};
$('#search').oninput=render;$('#save').onclick=save;window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}});
for(const [id,key] of [['f-number','number'],['f-name','name'],['f-title','title'],['f-subtitle','subtitle'],['f-description','description'],['f-extra','extraText'],['f-wiki','wikipedia']])$('#'+id).oninput=e=>{const entry=state.data.entries.find(x=>x.id===state.entryId);if(!state.dirty)snapshot();entry[key]=e.target.value;state.dirty=true;status('modifications en cours');if(key==='wikipedia')$('#open-wiki').href=e.target.value};
$('#dynamic-fields').oninput=e=>{const entry=state.data.entries.find(x=>x.id===state.entryId);entry.fields[e.target.dataset.dynamic]=e.target.value;state.dirty=true;status('modifications en cours')};$('#f-status').onchange=e=>change(()=>state.data.entries.find(x=>x.id===state.entryId).image.status=e.target.value);$('#f-locked').onchange=e=>change(()=>state.data.entries.find(x=>x.id===state.entryId).image.locked=e.target.checked);
$('#add-category').onclick=()=>{const name=prompt('Nom de la catégorie');if(name)change(()=>state.data.categories.push({id:crypto.randomUUID(),name,order:state.data.categories.length,deletedAt:null}))};$('#add-list').onclick=()=>{const name=prompt('Nom de la liste'),cat=state.data.categories.find(c=>!c.deletedAt);if(name&&cat)change(()=>{const l={id:crypto.randomUUID(),name,icon:'📚',categoryId:cat.id,columns:['Numéro','Image','Nom'],order:state.data.lists.length,metadata:{},deletedAt:null};state.data.lists.push(l);state.listId=l.id})};
$('#add-row').onclick=()=>change(()=>{const list=currentList(),e={id:crypto.randomUUID(),listId:list.id,number:String(entries().length+1),name:'Nouvelle entrée',title:'Nouvelle entrée',subtitle:'',description:'',extraText:'',wikipedia:'',fields:{},order:entries().length,deletedAt:null,externalIds:{},image:{source:null,full:null,thumb:null,crop:{cx:.5,cy:.5,w:1},status:'manquante',locked:false,provenance:{}}};state.data.entries.push(e);state.entryId=e.id});
$('#duplicate-row').onclick=()=>{const src=state.data.entries.find(e=>state.selected.has(e.id)||e.id===state.entryId);if(src)change(()=>state.data.entries.push({...structuredClone(src),id:crypto.randomUUID(),number:String(Number(src.number||0)+1),order:entries().length,image:{...src.image,locked:false}}))};$('#trash-row').onclick=()=>{if(!confirm('Placer la sélection dans la corbeille ?'))return;change(()=>state.data.entries.filter(e=>state.selected.has(e.id)||(state.selected.size===0&&e.id===state.entryId)).forEach(e=>{e.deletedAt=new Date().toISOString();state.data.trash.push({type:'entry',id:e.id,at:e.deletedAt})}))};
$('#renumber').onclick=()=>{const start=Number(prompt('Premier numéro',1));if(!start)return;const targets=state.selected.size?entries().filter(e=>state.selected.has(e.id)):entries();state.pendingDiff=targets.map((e,i)=>({id:e.id,field:'number',before:e.number,after:String(start+i)}));showDiff()};function showDiff(){$('#diff-content').innerHTML=state.pendingDiff.map(d=>`<div class="diff-row"><b>${esc(d.id.slice(0,12))}</b><span>${esc(d.before)}</span><b>→</b><span>${esc(d.after)}</span></div>`).join('');$('#diff-dialog').showModal()}$('#diff-apply').onclick=()=>change(()=>{for(const d of state.pendingDiff){const e=state.data.entries.find(x=>x.id===d.id);e[d.field]=d.after}state.pendingDiff=null;$('#diff-dialog').close()});
$('#undo').onclick=()=>{if(!state.undo.length)return;state.redo.push(JSON.stringify(state.data));state.data=JSON.parse(state.undo.pop());state.dirty=true;render()};$('#redo').onclick=()=>{if(!state.redo.length)return;state.undo.push(JSON.stringify(state.data));state.data=JSON.parse(state.redo.pop());state.dirty=true;render()};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#close-detail').onclick=()=>{$('.detail').classList.remove('mobile-open');state.entryId=null;renderDetail()};
$('#notes-view').onclick=$('#bulk-note').onclick=()=>{renderNotes();$('#notes-dialog').showModal()};function renderNotes(){$('#notes-list').innerHTML=state.data.notes.map(n=>`<div class="note"><b>${esc(n.status)} · ${esc(n.priority)}</b><p>${esc(n.text)}</p><small>${n.targets.entryIds.length} entrée(s), ${n.targets.listIds.length} liste(s)</small></div>`).join('')||'<p>Aucune note.</p>'}$('#note-add').onclick=()=>{const text=$('#note-text').value.trim();if(!text)return;change(()=>state.data.notes.push({id:crypto.randomUUID(),text,targets:{entryIds:[...state.selected],listIds:state.selected.size?[]:[state.listId]},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),status:$('#note-status').value,priority:$('#note-priority').value}));$('#note-text').value='';renderNotes()};
function updateImageInfo(){const out=$('#image-info');if(!editor?.source){out.textContent='Aucune image chargée';return}out.textContent=`Source ${editor.iw} × ${editor.ih} px · zoom ${Math.round(editor.scale/editor.minContain*100)} %`}
$('#edit-image').onclick=async()=>{const e=state.data.entries.find(x=>x.id===state.entryId);if(e.image?.locked&&!confirm('Cette image est verrouillée. La modifier ?'))return;$('#image-dialog').showModal();editor ||= new ImageEditor($('#image-frame'),$('#image-source'),$('#image-preview'),updateImageInfo);editor.clear();const source=e.image?.source||e.image?.full||e.image?.thumb;if(source)try{await editor.load('/'+source);editor.setCrop(e.image.crop);$('#image-empty').hidden=true}catch{editor.clear();$('#image-empty').hidden=false;alert('Image source illisible. Importez un nouveau fichier.')}else{$('#image-empty').hidden=false}updateImageInfo()};$('#img-file').onclick=()=>$('#img-input').click();$('#img-input').onchange=e=>loadFile(e.target.files[0]);async function loadFile(f){if(!f)return;await editor.load(URL.createObjectURL(f));$('#image-empty').hidden=true;updateImageInfo()}$('#image-frame').ondragover=e=>e.preventDefault();$('#image-frame').ondrop=e=>{e.preventDefault();loadFile(e.dataTransfer.files[0])};window.addEventListener('paste',e=>{if(!$('#image-dialog').open)return;const f=[...e.clipboardData.items].find(i=>i.type.startsWith('image/'))?.getAsFile();if(f)loadFile(f)});$('#img-fill').onclick=()=>editor.fill();$('#img-contain').onclick=()=>editor.contain();$('#img-center').onclick=()=>editor.recenter();$('#img-plus').onclick=()=>editor.zoom(1.2);$('#img-minus').onclick=()=>editor.zoom(1/1.2);$('#img-undo').onclick=()=>editor.back();$('#img-copy').onclick=async()=>{try{await editor.copy();status('image copiée')}catch{alert('La copie directe est bloquée par ce navigateur. Utilisez Télécharger.')}};$('#img-download').onclick=async()=>{const e=state.data.entries.find(x=>x.id===state.entryId);await editor.download(`${e?.name||'image'}.webp`)};
$('#img-save').onclick=async()=>{if(!editor?.source)return alert('Chargez une image avant de l’enregistrer.');const e=state.data.entries.find(x=>x.id===state.entryId),out=await editor.exports();for(const k of ['original','full','thumb']){const r=await fetch(`/api/image/${e.id}/${k}`,{method:'PUT',headers:{'Content-Type':'image/webp'},body:out[k]});if(!r.ok)return alert('Échec image');const j=await r.json();e.image[k==='original'?'source':k]=j.path}e.image.crop=editor.crop();e.image.status='importee';e.image.provenance={kind:'manual',at:new Date().toISOString()};state.dirty=true;status('modifications en cours');$('#image-dialog').close();render();await save()};
$('#import-wiki').onclick=()=>$('#import-dialog').showModal();$('#manifest-input').onchange=async e=>{state.manifest=JSON.parse(await e.target.files[0].text());const r=await fetch('/api/wikideck/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(state.manifest)}),report=await r.json();state.importReport=report;const count=k=>report.matches.filter(m=>m.status===k).length;$('#import-report').innerHTML=`<p><b>Analyse sans écriture</b></p><span class="badge">${count('certain')} certaines</span><span class="badge">${count('probable')} probables</span><span class="badge">${count('ambiguous')} ambiguës</span><span class="badge">${count('wikideck_only')} absentes de Mémo</span><p>Les images verrouillées ne seront jamais remplacées sans décision explicite. Les ambiguïtés et cartes absentes sont laissées pour décision manuelle.</p>`;$('#import-apply').hidden=false};
$('#import-apply').onclick=async()=>{if(!confirm('Appliquer uniquement les correspondances non ambiguës affichées ?'))return;const decisions=state.importReport.matches.filter(m=>['certain','probable'].includes(m.status)&&m.candidates.length===1).map(m=>({cardId:m.card.id,entryId:m.candidates[0].id}));const r=await fetch('/api/wikideck/apply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...state.manifest,confirm:true,decisions})}),j=await r.json();if(!r.ok)return alert(j.error||j.errors?.join('\n'));$('#import-report').innerHTML+=`<p><b>${j.results.filter(x=>x.status==='imported').length} image(s) importée(s).</b> ${j.results.filter(x=>x.status==='conflict').length} conflit(s) préservé(s).</p>`;await load()};
setInterval(()=>{if(state.dirty)save()},30000);load();
